### PR TITLE
Position Adding option , Font Size Option 

### PR DESCRIPTION
**Pull request by prio101**
Hello there @luthraG . I really liked your work. I was looking for something like that. its a great package. :+1: 
It seems , I also needed few things with it . So I added those options. And I noticed you also have few Issues regarding these options open right now. So I thought lets make a PR for that.

Here are the changes mostly I made:
- From now on user can specify position for the watermark text.
- From now on user can specify font size for the watermark text . And if not then it will be auto generated as before.
- I also updated the README.MD file accordingly .

Please let me know about your thoughts.

### CODE REVIEW

**Review by rohit5ram — APPROVED** [review]

**Comment by prio101** [comment]
Awesome :smile: .... Thanks

**Comment by imdkbj** [comment]
These changes are still not updated to the library.

**Comment by prio101** [comment]
ask @luthraG . He has to merge it.

**Comment by imdkbj** [comment]
@luthraG Just reinstalled on node but still not updated the library so might u forget to update the repo there. Pls also share the supported font list. I have tried many but found working only Arial and Courier by following method. May i missing something!!

`'font' :'Arial',`
or
`'font' :'Courier',`

**Pull request merged**
